import sampleImg from "../Assets/Banner/Banner.jpg";
import post1 from "../Assets/Posts/post3.jpg";
import jamaMasjid from "../Assets/Institute/84_big.jpg";
import sunherimasjid from "../Assets/Institute/sunehri-masjid.png";
import khanqah from "../Assets/Institute/Jama Masjid, Maulanapur.png";
import khanqah1 from "../Assets/Institute/Jama Masjid, Maulanapur1.png";
import jamamashjidhusainabad from "../Assets/Institute/Jama Masjid Hussainabad.png";
import MadrasaRazvia from "../Assets/Institute/Madrasa Razvia Shahbajul Uloom.png"
import MadrasaRazvia1 from "../Assets/Institute/Madrasa Razvia Shahbajul Uloom1.png"
import MadrasaRazvia2 from "../Assets/Institute/Madrasa Razvia Shahbajul Uloom2.png"
import BagmariMuslim from "../Assets/Institute/Bagmari Muslim Burial Ground.png"
import BagmariMuslim1 from "../Assets/Institute/Bagmari Muslim Burial Ground1.png"
import BagmariMuslim2 from "../Assets/Institute/Bagmari Muslim Burial Ground2.png"

const CombinedFeedData = [
  // USERS
  {
    id: 1,
    type: "user",
    username: "shabbeer",
    email: "shabbeer@gmail.com",
    password: "user123",
    avatar: post1,
    following: 200,
    location: "Khiribandh, Bhagalpur-Hansdiha Rd, Jamni, Bhairopur, Bihar 812005",
    transactions: [
      {
        id: 1,
        name: "Mashjid-e-hind",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 2,
        name: "Zakat",
        amount: 1500,
        date: "2025-07-01",
        type: "Zakat",
      },
      {
        id: 3,
        name: "Al-Noor Madrasa",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 4,
        name: "Khanqah-e-Rahmat",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 5,
        name: "Khiribandh Kabristan",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
    ],
  },
  {
    id: 2,
    type: "user",
    username: "foodie123",
    email: "foodie123@gmail.com",
    password: "foodie321",
    avatar: sampleImg,
    following: 340,
    location: "Bangalore",
    transactions: [
      {
        id: 1,
        name: "Mashjid-e-hind",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 2,
        name: "Zakat",
        amount: 1500,
        date: "2025-07-01",
        type: "Zakat",
      },
      {
        id: 3,
        name: "Al-Noor Madrasa",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 4,
        name: "Khanqah-e-Rahmat",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 5,
        name: "Khiribandh Kabristan",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
    ],
  },
  {
    id: 3,
    type: "institute",
    instituteType: "masjid",
    username: "Jama Masjid",
    email: "mashjid@gmail.com",
    password: "12345678",
    avatar: jamaMasjid,
    followers: 1050,
    location: "Haider Ganj Karah, Silao, Nalanda, Bihar: 803117",
    adhanTimes: {
      Fajr: "05:10",
      Dhuhr: "01:00",
      Asr: "16:20",
      Maghrib: "18:55",
      Isha: "20:15",
      Jumma: "12:30",
    },
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 3,
        name: "UPI4943223",
        transactionId: "UPI4943223",
        amount: 100,
        date: "2025-07-15",
        type: "withdraw",
      },
    ],
    posts: [
      {
        id: 1,
        type: "Quran",
        location: "Haider Ganj Karah, Silao, Nalanda, Bihar: 803117",
        likes: 720,
        time: "2025-05-11",
        title: "Surah Al-Fatiha",
        description: "Opening chapter of the Quran with deep meanings.",
        image: [jamaMasjid],
      },
      {
        id: 2,
        type: "Hadith",
        location: "Haider Ganj Karah, Silao, Nalanda, Bihar: 803117",
        likes: 520,
        time: "2025-05-10",
        title: "Virtue of Prayer",
        description: "Prophet (PBUH) emphasized the importance of Salah.",
        image: [jamaMasjid],
      },
    ],
  },
  {
    id: 4,
    type: "institute",
    instituteType: "madrasa",
    username: "Madrasa Razvia Shahbajul Uloom",
    email: "madarasa@gmail.com",
    password: "12345678",
    avatar: MadrasaRazvia,
    followers: 620,
    location: "Khiribandh, Bhagalpur-Hansdiha Rd, Jamni, Bhairopur, Bihar 812005",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 3,
        name: "UPI4943223",
        transactionId: "UPI4943223",
        amount: 500,
        date: "2025-07-15",
        type: "withdraw",
      },
    ],
    posts: [
      {
        id: 3,
        type: "Quran",
        location: "Khiribandh, Bhagalpur-Hansdiha Rd, Jamni, Bhairopur, Bihar 812005",
        likes: 450,
        time: "2025-05-08",
        title: "Surah Ikhlas",
        description: "Understanding monotheism in Islam.",
        image: [MadrasaRazvia, MadrasaRazvia1, MadrasaRazvia2],
      },
      {
        id: 4,
        type: "Quran",
        location: "Khiribandh, Bhagalpur-Hansdiha Rd, Jamni, Bhairopur, Bihar 812005",
        likes: 450,
        time: "2025-05-08",
        title: "Surah Ikhlas",
        description: "Understanding monotheism in Islam.",
        image: [MadrasaRazvia2, MadrasaRazvia],
      },
    ],
  },
  {
    id: 5,
    type: "institute",
    instituteType: "khanqah",
    username: "Jama Masjid, Maulanapur",
    email: "khanqah@gmail.com",
    password: "12345678",
    avatar: khanqah,
    followers: 800,
    location: "6XR9+2HW, Tilkamanjhi, Bhagalpur, Bihar 812002",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 3,
        name: "UPI4943223",
        transactionId: "UPI4943223",
        amount: 1000,
        date: "2025-07-15",
        type: "withdraw",
      },
    ],
    posts: [
      {
        id: 5,
        type: "Hadith",
        location: "6XR9+2HW, Tilkamanjhi, Bhagalpur, Bihar 812002",
        likes: 390,
        time: "2025-05-05",
        title: "Love for Humanity",
        description:
          "Hadith about loving for your brother what you love for yourself.",
        image: [khanqah, khanqah1],
      },
    ],
  },
  {
    id: 6,
    type: "institute",
    instituteType: "kabristan",
    username: "Bagmari Muslim Burial Ground",
    email: "kabristan@gmail.com",
    password: "kabristan123",
    avatar: BagmariMuslim,
    followers: 290,
    location: "Bagmari Lane, Kankurgachi, Kolkata, West Bengal 700054",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
      {
        id: 3,
        name: "UPI4943223",
        transactionId: "UPI4943223",
        amount: 800,
        date: "2025-07-15",
        type: "withdraw",
      },
    ],
    posts: [
      {
        id: 6,
        type: "Notice",
        location: "Bagmari Lane, Kankurgachi, Kolkata, West Bengal 700054",
        likes: 150,
        time: "2025-05-01",
        title: "Maintenance Update",
        description: "The kabristan will be closed for maintenance on Friday.",
        image: [BagmariMuslim, BagmariMuslim1, BagmariMuslim2],
      },
    ],
  },
  {
    id: 7,
    type: "institute",
    instituteType: "masjid",
    username: "Sunehri Masjid",
    email: "mashjid2@gmail.com",
    password: "12345678",
    avatar: sunherimasjid,
    followers: 1050,
    location:
      "Street-6, Kanti Nagar Extension, Block A, Seelampur, Shahdara, Delhi 110031",
    adhanTimes: {
      Fajr: "05:10",
      Dhuhr: "01:00",
      Asr: "16:20",
      Maghrib: "18:55",
      Isha: "20:15",
      Jumma: "12:30",
    },
    transactions: [],
    posts: [
      {
        id: 7,
        type: "Quran",
        location:
          "Street-6, Kanti Nagar Extension, Block A, Seelampur, Shahdara, Delhi 110031",
        likes: 720,
        time: "2025-05-11",
        title: "Surah Al-Fatiha",
        description: "Opening chapter of the Quran with deep meanings.",
        image: [sunherimasjid],
      },
    ],
  },
  {
    id: 8,
    type: "institute",
    instituteType: "masjid",
    username: "Jama Masjid Hussainabad",
    email: "mashjid3@gmail.com",
    password: "12345678",
    avatar: jamamashjidhusainabad,
    followers: 1050,
    location:
      "Hosainabad, KATGHAR LANE, Tilkamanjhi, Kutubganj, Bhagalpur, Bihar 812005",
    adhanTimes: {
      Fajr: "05:10",
      Dhuhr: "01:00",
      Asr: "16:20",
      Maghrib: "18:55",
      Isha: "20:15",
      Jumma: "12:30",
    },
    transactions: [],
    posts: [
      {
        id: 8,
        type: "Quran",
        location:
          "Hosainabad, KATGHAR LANE, Tilkamanjhi, Kutubganj, Bhagalpur, Bihar 812005",
        likes: 720,
        time: "2025-05-11",
        title: "Surah Al-Fatiha",
        description: "Opening chapter of the Quran with deep meanings.",
        image: [jamamashjidhusainabad],
      },
    ],
  },
];

export default CombinedFeedData;
