import sampleImg from "../Assets/Banner/Banner.jpg";
import post1 from "../Assets/Posts/post3.jpg";
import post2 from "../Assets/Posts/post4.jpg";
import post3 from "../Assets/Posts/vecteezy_islamic-cute-3d-mosque-for-ramadan-and-eid-greeting-background_26045410.jpg";
import avatarImg from "../Assets/Banner/Banner.jpg";

const CombinedFeedData = [
  // USERS
  {
    id: 1,
    type: "user",
    username: "shabbeer",
    email: "shabbeer@gmail.com",
    password: "user123",
    avatar: post1,
    following: 200,
    location: "Delhi",
    transactions: [
      {
        id: 1,
        name: "Mashjid-e-hind",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 2,
        name: "Zakat",
        amount: 1500,
        date: "2025-07-01",
        type: "Zakat",
      },
      {
        id: 3,
        name: "Al-Noor Madrasa",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 4,
        name: "Khanqah-e-Rahmat",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 5,
        name: "Khiribandh Kabristan",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
    ],
  },
  {
    id: 2,
    type: "user",
    username: "foodie123",
    email: "foodie123@gmail.com",
    password: "foodie321",
    avatar: sampleImg,
    following: 340,
    location: "Bangalore",
    transactions: [
      {
        id: 1,
        name: "Mashjid-e-hind",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 2,
        name: "Zakat",
        amount: 1500,
        date: "2025-07-01",
        type: "Zakat",
      },
      {
        id: 3,
        name: "Al-Noor Madrasa",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 4,
        name: "Khanqah-e-Rahmat",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 5,
        name: "Khiribandh Kabristan",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
    ],
  },
  {
    id: 3,
    type: "institute",
    instituteType: "masjid",
    username: "Mashjid-e-hind",
    email: "mashjid@gmail.com",
    password: "12345678",
    avatar: post1,
    followers: 1050,
    location: "Kolkata",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 100,
        date: "2025-07-01",
        type: "payment",
      },
    ],
    posts: [
      {
        id: 1,
        type: "Quran",
        location: "Delhi",
        likes: 720,
        time: "2025-05-11",
        title: "Surah Al-Fatiha",
        description: "Opening chapter of the Quran with deep meanings.",
        image: [post1, post2, post3],
      },
      {
        id: 2,
        type: "Hadith",
        location: "Gurgaon",
        likes: 520,
        time: "2025-05-10",
        title: "Virtue of Prayer",
        description: "Prophet (PBUH) emphasized the importance of Salah.",
        image: [sampleImg],
      },
    ],
  },
  {
    id: 4,
    type: "institute",
    instituteType: "madrasa",
    username: "Al-Noor Madrasa",
    email: "madarasa@gmail.com",
    password: "12345678",
    avatar: post2,
    followers: 620,
    location: "Patna",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 500,
        date: "2025-06-25",
        type: "payment",
      },
    ],
    posts: [
      {
        id: 1,
        type: "Quran",
        location: "Patna",
        likes: 450,
        time: "2025-05-08",
        title: "Surah Ikhlas",
        description: "Understanding monotheism in Islam.",
        image: [post3],
      },
      {
        id: 2,
        type: "Quran",
        location: "Patna",
        likes: 450,
        time: "2025-05-08",
        title: "Surah Ikhlas",
        description: "Understanding monotheism in Islam.",
        image: [post3],
      },
    ],
  },
  {
    id: 5,
    type: "institute",
    instituteType: "khanqah",
    username: "Khanqah-e-Rahmat",
    email: "khanqah@gmail.com",
    password: "12345678",
    avatar: post3,
    followers: 800,
    location: "Lucknow",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 1000,
        date: "2025-06-20",
        type: "payment",
      },
    ],
    posts: [
      {
        id: 1,
        type: "Hadith",
        location: "Lucknow",
        likes: 390,
        time: "2025-05-05",
        title: "Love for Humanity",
        description:
          "Hadith about loving for your brother what you love for yourself.",
        image: [post1],
      },
    ],
  },
  {
    id: 6,
    type: "institute",
    instituteType: "kabristan",
    username: "Khiribandh Kabristan",
    email: "kabristan@gmail.com",
    password: "kabristan123",
    avatar: avatarImg,
    followers: 290,
    location: "Bihar",
    transactions: [
      {
        id: 1,
        name: "shabbeer",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
      {
        id: 2,
        name: "foodie123",
        amount: 2500,
        date: "2025-05-10",
        type: "payment",
      },
    ],
    posts: [
      {
        id: 1,
        type: "Notice",
        location: "Bihar",
        likes: 150,
        time: "2025-05-01",
        title: "Maintenance Update",
        description: "The kabristan will be closed for maintenance on Friday.",
        image: [post2, post2],
      },
    ],
  },
];

export default CombinedFeedData;
